### ISSUE TITLE
Bootstrap 4 / Pimcore 4

### ISSUE THREAD

**Issue by cazy** [pimcore-extensions/bootstrap#13]
Hi,
I try to update your plugin to Pimcore 4/ Bootstrap 4.
What would you prefere? a new Branche?
Die you do some updates already? 
chris

**Comment by dpfaffenbauer** [comment]
hy,

just make your changes and create a pull-request. we can than tag the releases for 3.* or 4.*

**Comment by dpfaffenbauer** [comment]
Closed due to inactivity.
