### ISSUE TITLE
Area block templates not being found

### ISSUE THREAD

**Issue by Magepim** [pimcore-extensions/bootstrap#8]
Hi,

I've just installed your plugin to a Pimcore V3.06 install but it doesn't seem to find the area block templates unless I put them in the websites view/scripts folder.  I have converted all PHP short tags in the plugin.

**Comment by Hagith** [comment]
Views should be copied during installation by [this code](https://github.com/pimcore-extensions/bootstrap/blob/master/lib/Bootstrap/Plugin.php#L38).

Can you push pull request with short tags conversion.

**Comment by Magepim** [comment]
Maybe that was caused by having short tags or something then.  No problem, so manually copying them in has had the desired effect then.  Great.

I'll push a pull request later today with the short codes removed.

**Comment by Hagith** [comment]
Thanks
